---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# nasaprograminsights

```{r setup, eval=FALSE}
devtools::install_github(repo="NASA-Ecological-Conservation/nasaprograminsights", dependencies = FALSE, quiet = TRUE)
```

```{r make-data-locally, warnings=FALSE, eval=FALSE}
# Make a list of data frames using NSPIRES internal data ---------------------------------------------------------------
dir <-
  "/Users/jlburne3/Library/CloudStorage/OneDrive-NASA/bdecprogrameval/nspires-data/" # where is the internal data stored
nspires <-
  make_nspires(
    dir,
    removeppl = TRUE,
    tokeep = c(
      "selected",
      "declined",
      "submitted",
      "selectable",
      "invited",
      "awarded",
      "rejected"
    )
  )
# nspires contains 3 elements (data.frames):
##    lookup table to link program names and NOFOs
##    people: people listed on proposals
##    proposals: information regarding individual proposals
```

```{r inspect-data, eval=FALSE}
# Inspect Data ------------------------------------------------------------
# here is a list of EA programs
(programs <- nspires$lookup$`program name` |> unique() |> sort())
# here is a list of the programs for which we have proposal data:
# nspires$proposals[!nspires$proposals$`solicitation id` %in% nspires$lookup$`solciitation id`,] 
```
  
```{r simple-stats}

# ggplot()+
#   geom_histogram()

```
